// <auto-generated />
using System;
using Crm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crm.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("proposta_codigo_seq")
                .StartsAt(62632L);

            modelBuilder.Entity("Crm.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("CodigoCliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_cliente");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("principal");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("contatos", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.EmpresaEmissora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("endereco");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Site")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("site");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<string>("Unidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.ToTable("empresas_emissoras", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("formas_pagamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "A Vista"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "28 DDL"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Nome = "50% Entrada + 50% na Entrega"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Nome = "Cartão de Crédito / Débito"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Nome = "A Combinar"
                        });
                });

            modelBuilder.Entity("Crm.Domain.Entities.HistoricoInteracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<long>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId");

                    b.ToTable("historico_interacoes", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.ProdutoServico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<string>("DescricaoBase")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao_base");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grupo");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("preco_base");

                    b.HasKey("Id");

                    b.ToTable("produtos_servicos", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.Proposta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("ClausulasComerciais")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clausulas_comerciais");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<long>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("codigo")
                        .HasDefaultValueSql("nextval('proposta_codigo_seq')");

                    b.Property<long?>("ContatoId")
                        .HasColumnType("bigint")
                        .HasColumnName("contato_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<long>("EmpresaEmissoraId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_emissora_id");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("PrazoEntrega")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("A combinar")
                        .HasColumnName("prazo_entrega");

                    b.Property<long>("RepresentanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("representante_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<int>("ValidadeDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("validade_dias");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.Property<int>("Versao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ContatoId");

                    b.HasIndex("EmpresaEmissoraId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("RepresentanteId");

                    b.HasIndex("StatusId");

                    b.ToTable("propostas", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.PropostaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoItem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_item");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grupo");

                    b.Property<int>("ItemNumero")
                        .HasColumnType("integer")
                        .HasColumnName("item_numero");

                    b.Property<long?>("ProdutoServicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_servico_id");

                    b.Property<long>("PropostaId")
                        .HasColumnType("bigint")
                        .HasColumnName("proposta_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoServicoId");

                    b.HasIndex("PropostaId");

                    b.ToTable("proposta_itens", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.Representante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("representantes", (string)null);
                });

            modelBuilder.Entity("Crm.Domain.Entities.StatusProposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorHex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cor_hex");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("status_proposta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorHex = "#757575",
                            Descricao = "Proposta em elaboração",
                            Nome = "Rascunho"
                        },
                        new
                        {
                            Id = 2,
                            CorHex = "#1E88E5",
                            Descricao = "Enviada ao cliente",
                            Nome = "Enviada"
                        },
                        new
                        {
                            Id = 3,
                            CorHex = "#43A047",
                            Descricao = "Proposta aprovada pelo cliente",
                            Nome = "Aprovada"
                        },
                        new
                        {
                            Id = 4,
                            CorHex = "#E53935",
                            Descricao = "Proposta recusada pelo cliente",
                            Nome = "Recusada"
                        },
                        new
                        {
                            Id = 5,
                            CorHex = "#8E24AA",
                            Descricao = "Proposta cancelada internamente",
                            Nome = "Cancelada"
                        },
                        new
                        {
                            Id = 6,
                            CorHex = "#FB8C00",
                            Descricao = "Prazo de validade expirado",
                            Nome = "Expirada"
                        });
                });

            modelBuilder.Entity("Crm.Domain.Entities.Contato", b =>
                {
                    b.HasOne("Crm.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contatos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contatos_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Crm.Domain.Entities.HistoricoInteracao", b =>
                {
                    b.HasOne("Crm.Domain.Entities.Proposta", "Proposta")
                        .WithMany("Historico")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_proposta");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Crm.Domain.Entities.ProdutoServico", b =>
                {
                    b.OwnsOne("Crm.Domain.ValueObjects.EspecificacaoTecnica", "EspecificacoesPadrao", b1 =>
                        {
                            b1.Property<long>("ProdutoServicoId");

                            b1.Property<string>("Acabamento");

                            b1.Property<string>("Cores");

                            b1.Property<string>("Formato");

                            b1.Property<string>("Gramatura");

                            b1.Property<string>("Observacoes");

                            b1.Property<string>("Papel");

                            b1.HasKey("ProdutoServicoId");

                            b1.ToTable("produtos_servicos");

                            b1
                                .ToJson("EspecificacoesPadrao")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoServicoId");
                        });

                    b.Navigation("EspecificacoesPadrao")
                        .IsRequired();
                });

            modelBuilder.Entity("Crm.Domain.Entities.Proposta", b =>
                {
                    b.HasOne("Crm.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Propostas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propostas_cliente");

                    b.HasOne("Crm.Domain.Entities.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_propostas_contato");

                    b.HasOne("Crm.Domain.Entities.EmpresaEmissora", "EmpresaEmissora")
                        .WithMany("Propostas")
                        .HasForeignKey("EmpresaEmissoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propostas_empresa");

                    b.HasOne("Crm.Domain.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propostas_forma_pagamento");

                    b.HasOne("Crm.Domain.Entities.Representante", "Representante")
                        .WithMany("Propostas")
                        .HasForeignKey("RepresentanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propostas_representante");

                    b.HasOne("Crm.Domain.Entities.StatusProposta", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_propostas_status");

                    b.Navigation("Cliente");

                    b.Navigation("Contato");

                    b.Navigation("EmpresaEmissora");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Representante");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Crm.Domain.Entities.PropostaItem", b =>
                {
                    b.HasOne("Crm.Domain.Entities.ProdutoServico", "ProdutoServico")
                        .WithMany()
                        .HasForeignKey("ProdutoServicoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proposta_itens_produto");

                    b.HasOne("Crm.Domain.Entities.Proposta", "Proposta")
                        .WithMany("Itens")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposta_itens_proposta");

                    b.OwnsOne("Crm.Domain.ValueObjects.EspecificacaoTecnica", "Especificacoes", b1 =>
                        {
                            b1.Property<long>("PropostaItemId");

                            b1.Property<string>("Acabamento");

                            b1.Property<string>("Cores");

                            b1.Property<string>("Formato");

                            b1.Property<string>("Gramatura");

                            b1.Property<string>("Observacoes");

                            b1.Property<string>("Papel");

                            b1.HasKey("PropostaItemId");

                            b1.ToTable("proposta_itens");

                            b1
                                .ToJson("Especificacoes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PropostaItemId");
                        });

                    b.Navigation("Especificacoes")
                        .IsRequired();

                    b.Navigation("ProdutoServico");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("Crm.Domain.Entities.EmpresaEmissora", b =>
                {
                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Proposta", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Crm.Domain.Entities.Representante", b =>
                {
                    b.Navigation("Propostas");
                });
#pragma warning restore 612, 618
        }
    }
}
